ci: split docs deployment jobs

diff --git a/.github/workflows/preview-deploy.yml b/.github/workflows/preview-deploy.yml
--- a/.github/workflows/preview-deploy.yml
+++ b/.github/workflows/preview-deploy.yml
@@ -9,8 +9,8 @@ on:
       - completed
 
 jobs:
-  deploy-site:
-    name: deploy preview
+  deploy-cloudflare:
+    name: deploy preview to Cloudflare
     runs-on: ubuntu-latest
     if: >
       github.event.workflow_run.event == 'pull_request' &&
@@ -57,7 +57,39 @@ jobs:
           accountId: ${{ secrets.CF_ID }}
           command: pages deploy . --project-name=ant-design-blazor --branch=${{ steps.preview.outputs.branch }}
 
-      - name: update status comment
+  update-preview-comment:
+    name: update preview comment
+    needs: deploy-cloudflare
+    runs-on: ubuntu-latest
+    if: >
+      always() &&
+      github.event.workflow_run.event == 'pull_request' &&
+      github.event.workflow_run.conclusion == 'success' &&
+      needs.deploy-cloudflare.result == 'success'
+    steps:
+      - name: download pr artifact
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          workflow: ${{ github.event.workflow_run.workflow_id }}
+          name: pr
+
+      - name: save PR id
+        id: pr
+        run: |
+          PR_ID=$(cat pr-id.txt)
+          if ! [[ "$PR_ID" =~ ^[0-9]+$ ]]; then
+            echo "Invalid PR ID: Not a number"
+            exit 1
+          fi
+          echo "id=$PR_ID" >> $GITHUB_OUTPUT
+
+      - name: set Cloudflare preview branch
+        id: preview
+        env:
+          PR_ID: ${{ steps.pr.outputs.id }}
+        run: echo "branch=preview-pr-${PR_ID}" >> $GITHUB_OUTPUT
+
+      - name: Update status comment
         uses: actions-cool/maintain-one-comment@v1.1.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
@@ -67,8 +99,33 @@ jobs:
           body-include: '<!-- AUTO_PREVIEW_HOOK -->'
           number: ${{ steps.pr.outputs.id }}
 
-      - name: The job has failed
-        if: ${{ failure() }}
+  preview-deploy-failed:
+    name: report preview deploy failure
+    needs: deploy-cloudflare
+    runs-on: ubuntu-latest
+    if: >
+      always() &&
+      github.event.workflow_run.event == 'pull_request' &&
+      github.event.workflow_run.conclusion == 'success' &&
+      needs.deploy-cloudflare.result == 'failure'
+    steps:
+      - name: download pr artifact
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          workflow: ${{ github.event.workflow_run.workflow_id }}
+          name: pr
+
+      - name: save PR id
+        id: pr
+        run: |
+          PR_ID=$(cat pr-id.txt)
+          if ! [[ "$PR_ID" =~ ^[0-9]+$ ]]; then
+            echo "Invalid PR ID: Not a number"
+            exit 1
+          fi
+          echo "id=$PR_ID" >> $GITHUB_OUTPUT
+
+      - name: Report deploy failure
         uses: actions-cool/maintain-one-comment@v1.1.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
